### ISSUE TITLE
chrome 的控制台报错

### ISSUE THREAD

**Issue by Lovely-Ruby** [mumingfang/jvmaoTab#1]
chrome 的控制台报错了：
![image](https://github.com/user-attachments/assets/3bd529a1-2d3e-4e22-a7f1-a9fc93eca586)

```
Refused to load the script 'chrome-extension://3e305fe9-9c66-4c70-8126-5f94d5e850c1/static/js/src/content/index-e106e7e6.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

我目前的解决办法是 切换到 `onclick`

![image](https://github.com/user-attachments/assets/85b9ad5c-e15c-4793-9bb3-b97c9fc445ae)

**Comment by longlongvip** [comment]
我的报错
```js
createReactComponent-e34d357c.js:40 TypeError: Cannot read properties of undefined (reading 'key')
    at Home-4e2ad530.js:270:819
    at mo (LinkItem-668f51c4.js:34:13648)
    at jA (Home-4e2ad530.js:270:705)
    at index-12337d72.js:3:50518
    at index-12337d72.js:3:49695
    at Nh (index-12337d72.js:3:12185)
    at t.track (index-12337d72.js:3:17201)
    at ly (index-12337d72.js:3:49672)
    at a (index-12337d72.js:3:50497)
    at kg (createReactComponent…34d357c.js:38:19529)

```

**Comment by Lovely-Ruby** [comment]
我的问题解决了，`manifest.js` 中把这里删掉
![image](https://github.com/user-attachments/assets/8be6fa53-9b3a-43f0-b74c-4bd9de3406d0)

**Comment by mumingfang** [comment]
> 我的问题解决了，`manifest.js` 中把这里删掉 ![image](https://private-user-images.githubusercontent.com/24784282/387086669-8be6fa53-9b3a-43f0-b74c-4bd9de3406d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDQ1MTgsIm5iZiI6MTczMjEwNDIxOCwicGF0aCI6Ii8yNDc4NDI4Mi8zODcwODY2NjktOGJlNmZhNTMtOWIzYS00M2YwLWI3NGMtNGJkOWRlMzQwNmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEyMDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMDNiMjZiZGMyM2ViYmVhNjYzOWZkNmVhNWI2MzBlM2I1ZjQ4MTkwN2Q3MGFhMjM4ZjIwZmQ0MGI3YTBlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nD07Qn5pbhLpydyrmRdBr6CRDSIInEKZFNhl7h9mSiw)

你的浏览器版本是多少，我加这个是因为 130 之后改了相关协议

**Comment by mumingfang** [comment]
> 我的报错
> 
> ```js
> createReactComponent-e34d357c.js:40 TypeError: Cannot read properties of undefined (reading 'key')
>     at Home-4e2ad530.js:270:819
>     at mo (LinkItem-668f51c4.js:34:13648)
>     at jA (Home-4e2ad530.js:270:705)
>     at index-12337d72.js:3:50518
>     at index-12337d72.js:3:49695
>     at Nh (index-12337d72.js:3:12185)
>     at t.track (index-12337d72.js:3:17201)
>     at ly (index-12337d72.js:3:49672)
>     at a (index-12337d72.js:3:50497)
>     at kg (createReactComponent…34d357c.js:38:19529)
> ```

你可以单独开一贴，看样子应该是数据问题，可能需要发一下导出的数据

**Comment by longlongvip** [comment]
> > 我的报错
> > ```js
> > createReactComponent-e34d357c.js:40 TypeError: Cannot read properties of undefined (reading 'key')
> >     at Home-4e2ad530.js:270:819
> >     at mo (LinkItem-668f51c4.js:34:13648)
> >     at jA (Home-4e2ad530.js:270:705)
> >     at index-12337d72.js:3:50518
> >     at index-12337d72.js:3:49695
> >     at Nh (index-12337d72.js:3:12185)
> >     at t.track (index-12337d72.js:3:17201)
> >     at ly (index-12337d72.js:3:49672)
> >     at a (index-12337d72.js:3:50497)
> >     at kg (createReactComponent…34d357c.js:38:19529)
> > ```
> 
> 你可以单独开一贴，看样子应该是数据问题，可能需要发一下导出的数据

已开新的 issue
